### ISSUE TITLE
Incorporate feedback into report

### ISSUE THREAD

**Issue by tobiasvanderwerff** [tobiasvanderwerff/C20-Civil-Violence#26]
Incorporate the feedback (peer review and feedback from Malvin) into the report

**Comment by Wehzie** [comment]
Good idea: Epstein calls the protesting agents just "agents". This is confusing since the term agents is very general and in the context of multi agent systems may also mean the cop agents. Maybe we can find another term than agents for the protesters. For example protesters or civilians since they are not always protesting.
